---
source_directory: "spec/infra/vpc_link"
state_file: "%{hiera('project_directory')}/state/vpc_link.tfstate"
vars:
  region: "%{hiera('region')}"

  component: "%{hiera('component')}"
  deployment_identifier: "%{hiera('deployment_identifier')}"
